In [1]:
import numpy as np
import hddCRP.markovModeling as mm

In [2]:
# make sequence to fit (totally random)
K = 3
rng = np.random.Generator(np.random.MT19937(1023))
seq = rng.integers(0,K,size=(100))
symbols = range(K)


In [21]:
depth = 2 # how far back in time to care about dependencies (1=only look at previous action)

C = mm.get_transition_count(seq, depth=depth, symbols=symbols)
P = mm.get_transition_probabilities(C) # the plugin estimator for the transitions

# I also have some Bayesian estimation options
P1 = mm.get_transition_probabilities(C, alpha=1, rng=None) # add a regularization term in a simple categorical-dirichlet model for posterior mean estimates
P2 = mm.get_transition_probabilities(C, alpha=1, rng=rng) # can also draw P from the posterior over P under the categorical-dirichlet model
                                                          # This can help us figure out if the uncertainty in our estimates matters
P3 = mm.get_transition_probabilities_hierarchical(C, alpha=1, rng=None) #changes up the regularization using a very quick hierarchical scheme
P4 = mm.get_transition_probabilities_hierarchical(C, alpha=1, rng=rng) # 


[[0.21875    0.5        0.28125   ]
 [0.27272727 0.33333333 0.39393939]
 [0.44117647 0.17647059 0.38235294]]
[[0.22857143 0.48571429 0.28571429]
 [0.27777778 0.33333333 0.38888889]
 [0.43243243 0.18918919 0.37837838]]
[[0.23179246 0.57055135 0.19765618]
 [0.45910552 0.21798038 0.3229141 ]
 [0.34188308 0.20691829 0.45119862]]
[[0.22162805 0.49494949 0.28342246]
 [0.2739331  0.33333333 0.39273356]
 [0.43753501 0.18095238 0.38151261]]
[[0.24976689 0.47095545 0.27927766]
 [0.38866376 0.31639637 0.29493987]
 [0.43007047 0.16188608 0.40804345]]


In [27]:
initial_state = [0,1] # I ended up requiring an initial state to start the simulation - otherwise I wouldn't be sure how you'd want to begin
simulated_seqs = mm.simulate_from_model(P, initial_state, sim_length=100, rng=rng, nsims=10)
simulated_seqs # each column is one simulation (first steps are set to initial_state)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 0, 1, 0, 0, 0, 2, 0, 0, 2],
       [0, 0, 0, 2, 1, 0, 2, 2, 1, 1],
       [0, 2, 1, 2, 2, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 2, 2, 2, 1, 2, 0],
       [0, 2, 2, 1, 2, 0, 0, 1, 0, 2],
       [0, 2, 0, 2, 0, 2, 1, 1, 1, 1],
       [1, 0, 1, 0, 0, 2, 0, 1, 0, 2],
       [2, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 2, 1, 2, 1, 1, 2, 0, 2, 0],
       [1, 2, 1, 0, 0, 1, 2, 2, 0, 0],
       [2, 0, 1, 0, 1, 2, 0, 1, 1, 2],
       [2, 0, 0, 0, 1, 0, 1, 1, 2, 0],
       [2, 2, 1, 0, 2, 2, 1, 1, 1, 1],
       [2, 0, 2, 0, 2, 2, 2, 1, 0, 0],
       [0, 1, 0, 2, 0, 1, 2, 0, 1, 2],
       [2, 2, 2, 0, 1, 2, 2, 2, 0, 0],
       [0, 0, 0, 1, 0, 2, 2, 0, 1, 0],
       [1, 1, 0, 2, 1, 2, 0, 1, 0, 0],
       [2, 0, 2, 1, 2, 0, 0, 2, 1, 1],
       [0, 0, 1, 0, 1, 1, 2, 0, 0, 2],
       [1, 1, 0, 0, 2, 0, 2, 2, 1, 2],
       [1, 1, 1, 1, 1, 0, 2, 0, 1, 1],
       [2, 2, 1, 2, 2, 2, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 0,