In [1]:
import hddCRP.modelFitting
import hddCRP.simulations
import numpy as np

In [2]:
Y = np.array([0,1,2] * 2).reshape((2,3)).flatten(order='F')
Y = np.append(Y,Y)
N = Y.size;
grps = np.zeros((N,2),dtype=int)
grps[:6,1] = 1

D = np.ones((N,N))
alphas = [1,2];

print(Y)
print(grps.T)

[0 0 1 1 2 2 0 0 1 1 2 2]
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0 0 0]]


In [6]:
model = hddCRP.modelFitting.hddCRPModel(Y=Y, groupings=grps, alpha=alphas, D=D)
model._validate_internals("INIT")

In [7]:
codes = model.run_gibbs_sweep(DEBUG_MODE=True)
print(codes)

Connection type: 5
Connection type: 4
CB_num_labeled_upstream 
[[1 1 2 2 1 1 0 0 1 1 0 2]
 [1 1 1 1 1 1 1 1 1 1 1 2]]
C_num_labeled_upstream 
[[1 1 2 5 1 1 0 0 1 3 0 2]
 [1 1 1 1 1 1 1 1 1 1 1 2]]
recomputed num_labeled_upstream 
[[1 1 2 4 1 1 0 0 1 3 0 2]
 [1 1 1 1 1 1 1 1 1 1 1 2]]
Error found with code: 1


ValueError: _C_num_labeled_upstream has invalid counts

In [5]:
model._validate_print_before_and_after()

CB_tables_values 
[0 1 2 1]
CB_tables 
[[0 0 1 1 1 2 0 0 3 3 0 2]
 [0 0 1 1 2 2 0 0 3 3 2 2]]
CB_ptr 
[[ 7  7  3  4  3 11  0  1  8  8  6  5]
 [ 0  1  2  3  5  5  6  7  8  9 11 11]]
CB_is_cycle 
[[False  True False  True  True  True False  True  True False False  True]
 [False False False False False False False False False False False False]]
CB_y 
[[0 0 1 1 1 2 0 0 1 1 0 2]
 [0 0 1 1 2 2 0 0 1 1 2 2]]
CB_num_labeled_upstream 
[[2 1 1 2 0 2 1 3 2 1 0 2]
 [1 1 1 1 1 2 1 1 1 1 1 2]]
CB_num_labeled_in_table 
[4 2 4 2]
CB_predecessors 
[[[6], [7], [], [4, 2], [], [11], [10], [1, 0], [9], [3], [], [5]], [[], [], [], [], [], [4], [], [], [], [], [], [10]]]
C_table_values 
[0 1 2]
C_tables 
[[0 0 1 1 1 2 0 0 1 1 0 2]
 [0 0 1 1 2 2 0 0 1 1 2 2]]
C_ptr 
[[ 7  7  3  9  3 11  0  1  8  8  6  5]
 [ 0  1  2  3  5  5  6  7  8  9 11 11]]
C_is_cycle 
[[False  True False False False  True False  True  True False False  True]
 [False False False False False False False False False False False False]]


UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U5'), dtype('int32')) -> None

In [ ]:

connection_data= {"C_y" : model._C_y, "C_ctx" : grps, "session_lengths" : [model.N]}
ax = plt.gca()
hddCRP.simulations.make_graph_plot(connection_data, ax)
plt.show

In [ ]:

print(model._C_y)
print(model._C_y_0)

In [ ]:
print(model._C_is_cycle.T)

In [ ]:
print(model._C_predecessors)

In [ ]:
print(np.sum(model._C_y_0[model._C_tables == 1] != -1))
np.array([np.sum(model._C_y_0[model._C_tables == tt] != -1) 
                                                for tt in range(model._C_table_counter)], dtype=int)